platform :ios, '8.0'
inhibit_all_warnings!

target 'Dolores' do
	pod 'HyphenateLite'
	pod 'EaseUILite', :git =>'https://github.com/easemob/easeui-ios-hyphenate-cocoapods.git'
	pod 'Masonry', '~> 1.0.0'
    pod 'ReactiveObjC', '~> 2.1.2'
    pod 'YYCategories'
    
end

